// <auto-generated />
using System;
using ConfRadar.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConfRadar.Repositories.Migrations
{
    [DbContext(typeof(ConfRadarDbContext))]
    [Migration("20251020190131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfRadar.Repositories.Models.Conference", b =>
                {
                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("ConferenceCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ConferenceRankingId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("GlobalStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInternalHosted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsResearchConference")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ConferenceId")
                        .HasName("Conference_pkey");

                    b.HasIndex("ConferenceCategoryId");

                    b.ToTable("Conference", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceCategory", b =>
                {
                    b.Property<string>("ConferenceCategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceCategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ConferenceCategoryId")
                        .HasName("ConferenceCategory_pkey");

                    b.ToTable("ConferenceCategory", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceMedium", b =>
                {
                    b.Property<string>("ConferenceMediaId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceMediaUrl")
                        .HasColumnType("text");

                    b.Property<string>("MediaTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ConferenceMediaId")
                        .HasName("ConferenceMedia_pkey");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("ConferenceMedia");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferencePolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("PolicyId")
                        .HasName("ConferencePolicy_pkey");

                    b.HasIndex("ConferenceId");

                    b.ToTable("ConferencePolicy", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferencePrice", b =>
                {
                    b.Property<string>("ConferencePriceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ActualPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PricePhaseId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TicketDescription")
                        .HasColumnType("text");

                    b.Property<string>("TicketName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("TicketPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("ConferencePriceId")
                        .HasName("ConferencePrice_pkey");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("PricePhaseId");

                    b.ToTable("ConferencePrice", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceSession", b =>
                {
                    b.Property<string>("ConferenceSessionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ConferenceSessionId")
                        .HasName("ConferenceSession_pkey");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("RoomId");

                    b.ToTable("ConferenceSession", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Destination", b =>
                {
                    b.Property<string>("DestinationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DestinationId")
                        .HasName("Destination_pkey");

                    b.ToTable("Destination", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.FavouriteConference", b =>
                {
                    b.Property<string>("FavouriteConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("FavouriteConferenceId")
                        .HasName("FavouriteConference_pkey");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("UserId");

                    b.ToTable("FavouriteConference", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.GlobalStatus", b =>
                {
                    b.Property<string>("GlobalStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GlobalStatusId")
                        .HasName("GlobalStatus_pkey");

                    b.ToTable("GlobalStatus", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.MediaType", b =>
                {
                    b.Property<string>("MediaTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MediaTypeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MediaTypeId")
                        .HasName("MediaType_pkey");

                    b.ToTable("MediaType", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MethodDescription")
                        .HasColumnType("text");

                    b.Property<string>("MethodName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PaymentMethod_pkey");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.PricePhase", b =>
                {
                    b.Property<string>("PricePhaseId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("EarlierBirdEndInterval")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LateEndInterval")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PercentForEarly")
                        .HasColumnType("integer");

                    b.Property<int?>("PercentForEnd")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StandardEndInterval")
                        .HasColumnType("date");

                    b.HasKey("PricePhaseId")
                        .HasName("PricePhase_pkey");

                    b.ToTable("PricePhase", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.RefundRequest", b =>
                {
                    b.Property<string>("RefundRequestId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GlobalStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TicketId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RefundRequestId")
                        .HasName("RefundRequest_pkey");

                    b.HasIndex("GlobalStatusId");

                    b.HasIndex("TransactionId");

                    b.HasIndex(new[] { "TicketId" }, "RefundRequest_TicketId_key")
                        .IsUnique();

                    b.ToTable("RefundRequest", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("RoleId")
                        .HasName("Role_pkey");

                    b.HasIndex(new[] { "RoleName" }, "Role_RoleName_key")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DestinationId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Number")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RoomId")
                        .HasName("Room_pkey");

                    b.HasIndex("DestinationId");

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Speaker", b =>
                {
                    b.Property<string>("ConferenceSessionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ConferenceSessionId")
                        .HasName("Speaker_pkey");

                    b.ToTable("Speaker", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Sponsor", b =>
                {
                    b.Property<string>("SponsorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SponsorId")
                        .HasName("Sponsor_pkey");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Sponsor", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("StatusId")
                        .HasName("Status_pkey");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TechnicalConferenceDetail", b =>
                {
                    b.Property<string>("ConferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("text");

                    b.HasKey("ConferenceId")
                        .HasName("TechnicalConferenceDetail_pkey");

                    b.ToTable("TechnicalConferenceDetail", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Ticket", b =>
                {
                    b.Property<string>("TicketId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ActualPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ConferencePriceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsRefunded")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RegisteredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TicketId")
                        .HasName("Ticket_pkey");

                    b.HasIndex("ConferencePriceId");

                    b.HasIndex("UserId");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TicketId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("text");

                    b.Property<string>("TransactionStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TransactionTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TransactionId")
                        .HasName("Transaction_pkey");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TransactionStatusId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TransactionStatus", b =>
                {
                    b.Property<string>("TransactionStatusId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TransactionStatusId")
                        .HasName("TransactionStatus_pkey");

                    b.ToTable("TransactionStatus", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TransactionType", b =>
                {
                    b.Property<string>("TransactionTypeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeDescription")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TransactionTypeId")
                        .HasName("TransactionType_pkey");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("BioDescription")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Email" }, "User_Email_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.UserRefreshToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Expiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TokenId")
                        .HasName("UserRefreshToken_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Token" }, "UserRefreshToken_Token_key")
                        .IsUnique();

                    b.ToTable("UserRefreshToken", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "RoleId")
                        .HasName("UserRole_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Conference", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.ConferenceCategory", "ConferenceCategory")
                        .WithMany("Conferences")
                        .HasForeignKey("ConferenceCategoryId")
                        .HasConstraintName("Conference_ConferenceCategoryId_fkey");

                    b.Navigation("ConferenceCategory");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceMedium", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("ConferenceMedia")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceMedia_ConferenceId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.MediaType", "MediaType")
                        .WithMany("ConferenceMedia")
                        .HasForeignKey("MediaTypeId")
                        .HasConstraintName("ConferenceMedia_MediaTypeId_fkey");

                    b.Navigation("Conference");

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferencePolicy", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("ConferencePolicies")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferencePolicy_ConferenceId_fkey");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferencePrice", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("ConferencePrices")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferencePrice_ConferenceId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.PricePhase", "PricePhase")
                        .WithMany("ConferencePrices")
                        .HasForeignKey("PricePhaseId")
                        .HasConstraintName("ConferencePrice_PricePhaseId_fkey");

                    b.Navigation("Conference");

                    b.Navigation("PricePhase");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceSession", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("ConferenceSessions")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("ConferenceSession_ConferenceId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.Room", "Room")
                        .WithMany("ConferenceSessions")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("ConferenceSession_RoomId_fkey");

                    b.Navigation("Conference");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.FavouriteConference", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("FavouriteConferences")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("FavouriteConference_ConferenceId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.User", "User")
                        .WithMany("FavouriteConferences")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FavouriteConference_UserId_fkey");

                    b.Navigation("Conference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.RefundRequest", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.GlobalStatus", "GlobalStatus")
                        .WithMany("RefundRequests")
                        .HasForeignKey("GlobalStatusId")
                        .HasConstraintName("RefundRequest_GlobalStatusId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.Ticket", "Ticket")
                        .WithOne("RefundRequest")
                        .HasForeignKey("ConfRadar.Repositories.Models.RefundRequest", "TicketId")
                        .HasConstraintName("RefundRequest_TicketId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.Transaction", "Transaction")
                        .WithMany("RefundRequests")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("RefundRequest_TransactionId_fkey");

                    b.Navigation("GlobalStatus");

                    b.Navigation("Ticket");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Room", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Destination", "Destination")
                        .WithMany("Rooms")
                        .HasForeignKey("DestinationId")
                        .HasConstraintName("Room_DestinationId_fkey");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Speaker", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.ConferenceSession", "ConferenceSession")
                        .WithOne("Speaker")
                        .HasForeignKey("ConfRadar.Repositories.Models.Speaker", "ConferenceSessionId")
                        .IsRequired()
                        .HasConstraintName("Speaker_ConferenceSessionId_fkey");

                    b.Navigation("ConferenceSession");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Sponsor", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithMany("Sponsors")
                        .HasForeignKey("ConferenceId")
                        .HasConstraintName("Sponsor_ConferenceId_fkey");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TechnicalConferenceDetail", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Conference", "Conference")
                        .WithOne("TechnicalConferenceDetail")
                        .HasForeignKey("ConfRadar.Repositories.Models.TechnicalConferenceDetail", "ConferenceId")
                        .IsRequired()
                        .HasConstraintName("TechnicalConferenceDetail_ConferenceId_fkey");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Ticket", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.ConferencePrice", "ConferencePrice")
                        .WithMany("Tickets")
                        .HasForeignKey("ConferencePriceId")
                        .HasConstraintName("Ticket_ConferencePriceId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Ticket_UserId_fkey");

                    b.Navigation("ConferencePrice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Transaction", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("Transaction_PaymentMethodId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.Ticket", "Ticket")
                        .WithMany("Transactions")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("Transaction_TicketId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.TransactionStatus", "TransactionStatus")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionStatusId")
                        .HasConstraintName("Transaction_TransactionStatusId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .HasConstraintName("Transaction_TransactionTypeId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Transaction_UserId_fkey");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Ticket");

                    b.Navigation("TransactionStatus");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.UserRefreshToken", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.User", "User")
                        .WithMany("UserRefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UserRefreshToken_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.UserRole", b =>
                {
                    b.HasOne("ConfRadar.Repositories.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("UserRole_RoleId_fkey");

                    b.HasOne("ConfRadar.Repositories.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UserRole_UserId_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Conference", b =>
                {
                    b.Navigation("ConferenceMedia");

                    b.Navigation("ConferencePolicies");

                    b.Navigation("ConferencePrices");

                    b.Navigation("ConferenceSessions");

                    b.Navigation("FavouriteConferences");

                    b.Navigation("Sponsors");

                    b.Navigation("TechnicalConferenceDetail");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceCategory", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferencePrice", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.ConferenceSession", b =>
                {
                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Destination", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.GlobalStatus", b =>
                {
                    b.Navigation("RefundRequests");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.MediaType", b =>
                {
                    b.Navigation("ConferenceMedia");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.PricePhase", b =>
                {
                    b.Navigation("ConferencePrices");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Room", b =>
                {
                    b.Navigation("ConferenceSessions");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Ticket", b =>
                {
                    b.Navigation("RefundRequest");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.Transaction", b =>
                {
                    b.Navigation("RefundRequests");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TransactionStatus", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ConfRadar.Repositories.Models.User", b =>
                {
                    b.Navigation("FavouriteConferences");

                    b.Navigation("Tickets");

                    b.Navigation("Transactions");

                    b.Navigation("UserRefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
