name: GFA25SE75

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /root/sep490/ConfRadar_BE/ConfRadar
            git pull origin main

            printf "%s\n" '${{ secrets.APPSETTINGS_JSON }}' > ConfRadar.Api/appsettings.json
            printf "%s\n" '${{ secrets.ENV }}' > .env
            printf "%s\n" '${{ secrets.CONFRADAR_ADMIN_SDK }}' > ConfRadar.Api/confradar-admin-sdk.json

            
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker image prune -af
            docker builder prune -af